In [1]:
import pandas as pd

In [2]:
df= pd.read_csv('../data/complaints.csv')

In [3]:
df.head()

,ComplaintID,Complaint,Category,Urgency
0,CMP_10001,The indoor gym equipment cable snapped while a...,Sports,High
1,CMP_10002,"The authentication gateway server is down, pre...",Internet,High
2,CMP_10003,A large chunk of plaster fell from the ceiling...,Hostel,Critical
3,CMP_10004,the exam paper leaked online an hour prior to ...,Academic,High
4,CMP_10005,Rainwater is rally leaking from the roof direc...,Library,High

In [4]:
df.shape

(5000, 4)

In [5]:
df.isna().sum()

ComplaintID    0
Complaint      0
Category       0
Urgency        0
dtype: int64

In [6]:
df.describe()

,ComplaintID,Complaint,Category,Urgency
count,5000,5000,5000,5000
unique,5000,1124,12,4
top,CMP_10001,A major collision involving the university tra...,Internet,Low
freq,1,58,417,1372

In [7]:
df['Category'].value_counts()

Category
Internet       417
Hostel         417
Library        417
Electricity    417
Transport      417
Laboratory     417
Plumbing       417
Mess           417
Sports         416
Academic       416
Medical        416
Security       416
Name: count, dtype: int64

In [9]:
df['Urgency'].value_counts()

Urgency
Low         1372
High        1234
Critical    1197
Medium      1197
Name: count, dtype: int64

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   ComplaintID  5000 non-null   str
 1   Complaint    5000 non-null   str
 2   Category     5000 non-null   str
 3   Urgency      5000 non-null   str
dtypes: str(4)
memory usage: 156.4 KB